<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="6" hostname="GunMetal-01" failures="1" tests="3" name="JavafxProject" time="1.355" errors="0" timestamp="30 Nov 2020 10:19:49 GMT">
  <testcase classname="persistence.StaffDAOTest" name="testValidateUserTrue" time="1.143"/>
  <testcase classname="persistence.StaffDAOTest" name="testValidateUser" time="0.058">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at persistence.StaffDAOTest.testValidateUser(StaffDAOTest.java:36)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:110)
at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:131)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- testValidateUser -->
  <testcase classname="persistence.StaffDAOTest" name="testValidateUserFalse" time="0.078"/>
  <testcase classname="persistence.StaffDAOTest" name="testUpdateLockedData" time="0.0">
    <ignored/>
  </testcase> <!-- testUpdateLockedData -->
  <testcase classname="persistence.StaffDAOTest" name="testCheckIfExists" time="0.0">
    <ignored/>
  </testcase> <!-- testCheckIfExists -->
  <testcase classname="persistence.StaffDAOTest" name="testAddUser" time="0.0">
    <ignored/>
  </testcase> <!-- testAddUser -->
  <testcase classname="persistence.StaffDAOTest" name="testGetAllStaff" time="0.0">
    <ignored/>
  </testcase> <!-- testGetAllStaff -->
  <testcase classname="persistence.StaffDAOTest" name="testGetRole" time="0.0">
    <ignored/>
  </testcase> <!-- testGetRole -->
  <testcase classname="persistence.StaffDAOTest" name="testDeleteUser" time="0.0">
    <ignored/>
  </testcase> <!-- testDeleteUser -->
</testsuite> <!-- JavafxProject -->
